### ISSUE TITLE
FatalTraCIError Question.

### ISSUE THREAD

**Issue by jylee3302** [eclipse-sumo/sumo#11362]
Add your issue description here.

*If possible, upload an example that shows your problem.*

Below is the error code and I'm not sure why FatalTraCIError happens. I was trying to reproduce why this happens, but not yet. Is there any clue I can rely on to solve this problem? I'm running multiple SUMOs using joblib (with different port numbers) and have no idea why traci.simulation.findRoute crashes..

I'm using a Linux super computer + installed xerces 3.2.3 + loaded intel 19.1.1 + cmake during its installation for dependencies.

=======================================================================
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/myworkspace/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/myworkspace/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/myworkspace/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/myworkspace/.local/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/myworkspace/.local/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/myworkspace/software/code/savParallel/savParallel.py", line 804, in runEVAC
    rerouteTT += traci.simulation.findRoute(start, edge,
  File "/myworkspace/.local/lib/python3.9/site-packages/traci/_simulation.py", line 597, in findRoute
    return self._getUniversal(tc.FIND_ROUTE, "", "tsssdi", 5, fromEdge, toEdge, vType, depart, routingMode)
  File "/myworkspace/.local/lib/python3.9/site-packages/traci/domain.py", line 147, in _getUniversal
    return _parse(self._retValFunc, varID, self._getCmd(varID, objectID, format, *values))
  File "/myworkspace/.local/lib/python3.9/site-packages/traci/domain.py", line 152, in _getCmd
    r = self._connection._sendCmd(self._cmdGetID, varID, objID, format, *values)
  File "/myworkspace/.local/lib/python3.9/site-packages/traci/connection.py", line 189, in _sendCmd
    return self._sendExact()
  File "/myworkspace/.local/lib/python3.9/site-packages/traci/connection.py", line 99, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/myworkspace/software/code/savParallel/savParallel.py", line 1941, in <module>
    runParallel()
  File "/myworkspace/software/code/savParallel/savParallel.py", line 10, in runParallel
    simulSummary = Parallel(n_jobs=50)(delayed(runEVAC)(repeat, rootFolder, sumoBinary) for repeat in range(0, 49))  # order 0
  File "/myworkspace/.local/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/myworkspace/.local/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/myworkspace/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
traci.exceptions.FatalTraCIError: connection closed by SUMO

**SUMO-version:**
1.14.1

**operating system:**
Linux

**Comment by m-kro** [comment]
In first place, FatalTraCIError indicates only that SUMO has crashed, but not why it did. Any TraCI command after the crash will fail and generate a FatalTraCIError. 

Can you identify which of your simulation runs failed and try to reproduce it in a single run? Then we would be interested in the simulation scenario and a [TraCI log](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands) to check it ourselves.
