### ISSUE TITLE
Error: Invalid empty condition when running tracI with multi agent RL for traffic signal control

### ISSUE THREAD

**Issue by Mehdi-Inane** [eclipse-sumo/sumo#13764]
Hello,

I am running this program https://github.com/LucasAlegre/sumo-rl/ for traffic signal control for a custom large scale traffic scenario representing downtown Athens. The SUMO data can be found in this link : https://we.tl/t-hiF2BuRCSL
My problem is whenever I run this code https://github.com/LucasAlegre/sumo-rl/blob/main/experiments/sarsa_resco.py on my network, I get the following error that I cannot debug, since no other information is provided : 
Error: Invalid empty condition ''97.01UPS, TraCI: 795ms, vehicles TOT 417 ACT 417 BUF 5909
Quitting (on error).
Traceback (most recent call last):
  File "/mnt/c/users/inane/Downloads/sumo-rl/experiments/sarsa_resco.py", line 181, in <module>
    fire.Fire(run)
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/c/users/inane/Downloads/sumo-rl/experiments/sarsa_resco.py", line 171, in run
    next_obs, r, done,terminated, info = env.step(actions=actions)
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/pettingzoo/utils/conversions.py", line 191, in step
    self.aec_env.step(actions[agent])
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 81, in step
    super().step(action)
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/pettingzoo/utils/wrappers/base.py", line 116, in step
    self.env.step(action)
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/pettingzoo/utils/wrappers/assert_out_of_bounds.py", line 29, in step
    super().step(action)
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/pettingzoo/utils/wrappers/base.py", line 116, in step
    self.env.step(action)
  File "/mnt/c/users/inane/Downloads/sumo-rl/sumo_rl/environment/env.py", line 587, in step
    self.env._run_steps()
  File "/mnt/c/users/inane/Downloads/sumo-rl/sumo_rl/environment/env.py", line 328, in _run_steps
    self._sumo_step()
  File "/mnt/c/users/inane/Downloads/sumo-rl/sumo_rl/environment/env.py", line 403, in _sumo_step
    self.sumo.simulationStep()
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/traci/connection.py", line 366, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/traci/connection.py", line 228, in _sendCmd
    return self._sendExact()
  File "/home/mehdi_inane/anaconda3/lib/python3.9/site-packages/traci/connection.py", line 137, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

Do you have an idea of where this could stem from ? I have even tried to control a single traffic light but the same scenario happens. The code works however for other scenarios with multiple traffic lights.

**SUMO-version: version 1.18.0**
Thanks in advance for your help !

**Comment by robertalms** [comment]
Hi, can you please clarify again if your test instantiates a single or multi agent experiment?

I used SUMO-RL for single agent control some years ago, which worked fine, but haven't tested the multi agent upgrade since then. Note that mulit agent RL can be tricky, because SUMO does not support multi threading... I have tested other scenarios with stable-baselines3, where the library correctly created mulitple envs with distinctive traci connections - so it should work, if the pettingzoo-wrapper you use, does the same correcty.

Debugging RL scenarios with SUMO is not easy because its a hassle to replicate the error for others without the full code base.

**Comment by behrisch** [comment]
closing for lack of feedback. If you have more information, please add another comment
