### ISSUE TITLE
libsumo can't support multi-thread?

### ISSUE THREAD

**Issue by Freedomisgood** [eclipse-sumo/sumo#14176]
Add your issue description here.

i want to connect to some SUMO instance at the same time, so i use multi-thread programming, when I use traci, the program works, but when I switch to libsumo, it's very easy to raise `libsumo.libsumo.FatalTraCIError: A network was not yet constructed.`, I guess whether libsumo supports multi-thread? thanls

*If possible, upload an example that shows your problem.*
```

Traceback (most recent call last):
  File "E:/aDevelopment/Python/sciLearn/tl/intelli-tls-mrli/experiments/multi/marppo_gnn_paral_experiment.py", line 238, in <module>
    marppo_experiment.do_train()
  File "E:\aDevelopment\Python\sciLearn\tl\intelli-tls-mrli\experiments\rl_experiment_parl.py", line 115, in do_train
    self._train()
  File "E:/aDevelopment/Python/sciLearn/tl/intelli-tls-mrli/experiments/multi/marppo_gnn_paral_experiment.py", line 171, in _train
    total_steps += (fut.result() + 1)
  File "c:\users\10630\.pyenv\pyenv-win\versions\3.8.10\lib\concurrent\futures\_base.py", line 444, in result
    return self.__get_result()
  File "c:\users\10630\.pyenv\pyenv-win\versions\3.8.10\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "c:\users\10630\.pyenv\pyenv-win\versions\3.8.10\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:/aDevelopment/Python/sciLearn/tl/intelli-tls-mrli/experiments/multi/marppo_gnn_paral_experiment.py", line 101, in run_once_episode
    _, r, done, info = env.step(a_n)  # Take a step
  File "E:\aDevelopment\Python\sciLearn\tl\intelli-tls-mrli\core\envs\sumo.py", line 319, in step
    self._apply_actions(action)
  File "E:\aDevelopment\Python\sciLearn\tl\intelli-tls-mrli\core\envs\sumo.py", line 548, in _apply_actions
    self.traffic_lights[str(i)].set_next_phase(actions[i])
  File "E:\aDevelopment\Python\sciLearn\tl\intelli-tls-mrli\core\traffic_lights\sumo.py", line 217, in set_next_phase
    self.sumo.trafficlight.setRedYellowGreenState(self.id, self.all_phases[self.yellow_dict[(self.green_phase, new_phase)]].state)
  File "D:\SUMO\tools\libsumo\libsumo.py", line 4617, in setRedYellowGreenState
    return _libsumo.trafficlight_setRedYellowGreenState(tlsID, state)
libsumo.libsumo.FatalTraCIError: A network was not yet constructed.

Process finished with exit code 1
```

**SUMO-version:**
1.15.0

**operating system:**
windows11 and  Ubuntu 20.04.4 LTS

**Comment by behrisch** [comment]
This error usually means that you did not issue the start command beforehand or that you already closed the simulation. Parallel execution should be possible but there have been many fixes to that in the past year, so please retry with a newer version and make sure you only issue start and close from one thread

**Comment by m-kro** [comment]
Closing due to lack of feedback
