### ISSUE TITLE
Xml2csv error on Windows 11

### ISSUE THREAD

**Issue by Lookingforcommit** [eclipse-sumo/sumo#14218]
When I'm trying to create a csv file using the "xml2csv" tool I am receiving this error message
```
Traceback (most recent call last):
  File "E:\sumo\tools\xml\xml2csv.py", line 286, in <module>
    main()
  File "E:\sumo\tools\xml\xml2csv.py", line 270, in main
    attrFinder = AttrFinder(options.xsd, options.source, options.split)
  File "E:\sumo\tools\xml\xml2csv.py", line 88, in __init__
    xml.sax.parse(source, self)
  File "C:\Users\itmas\AppData\Local\Programs\Python\Python310\lib\xml\sax\__init__.py", line 33, in parse
    parser.parse(source)
  File "C:\Users\itmas\AppData\Local\Programs\Python\Python310\lib\xml\sax\expatreader.py", line 105, in parse
    source = saxutils.prepare_input_source(source)
  File "C:\Users\itmas\AppData\Local\Programs\Python\Python310\lib\xml\sax\saxutils.py", line 365, in prepare_input_source
    f = urllib.request.urlopen(source.getSystemId())
  File "C:\Users\itmas\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\itmas\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 503, in open
    req = Request(fullurl, data)
  File "C:\Users\itmas\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 322, in __init__
    self.full_url = url
  File "C:\Users\itmas\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 348, in full_url
    self._parse()
  File "C:\Users\itmas\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'RawDump.xml'
``` 
The command I am running looks like this: "python sumo/tools/xml/xml2csv.py RawDump.xml", the "RawDump.xml" file is located in the "sumo/tools/xml" directory. 
My python version is 3.10.4

**Comment by m-kro** [comment]
If you give just the file name to read it means the file has to be in the current working directory, which seems to be one up of "sumo". Either add the path to the xml file to read or change the working directory to sumo/tools/xml.

**Comment by Lookingforcommit** [comment]
Thank you, changing the working directory did fix the problem)
