### ISSUE TITLE
Issues with running sumo for pedestrian crossing 

### ISSUE THREAD

**Issue by khzannat** [eclipse-sumo/sumo#14307]
I am modelling a pedestrian crossing which switches on demand. I am using TraCI interface and tutorial runner.py.
The example code run properly. Then I modified my network that included the pedestrian crossing initial tllogic. I added the pedestrian flow using  pedestrians.trip.xml and  car demand using another xml. With my given network, separate pedestrian flow and car flow simulation runs without interruption. While I combine both to switch on the pedestrian crossing I am having the following error:

Traceback (most recent call last):                                                                                                                                        File "C:\Users\Zannat\runner.py", line 158, in <module>                                                                                                                   run()                                                                                                                                                                 File "C:\Users\Zannat\runner.py", line 81, in run                                                                                                                         activeRequest = checkWaitingPersons()                                                                                                                                                   ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                 File "C:\Users\Zannat\runner.py", line 111, in checkWaitingPersons                                                                                                        numWaiting = traci.trafficlight.getServedPersonCount(TLSID, PEDESTRIAN_GREEN_PHASE)                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                   File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\_trafficlight.py", line 244, in getServedPersonCount                                                                return self._getUniversal(tc.VAR_PERSON_NUMBER, tlsID, "i", index)                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                    File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\domain.py", line 147, in _getUniversal                                                                              return _parse(self._retValFunc, varID, self._getCmd(varID, objectID, format, *values))                                                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                 File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\domain.py", line 152, in _getCmd                                                                                    r = self._connection._sendCmd(self._cmdGetID, varID, objID, format, *values)                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                          File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 231, in _sendCmd                                                                               return self._sendExact()                                                                                                                                                       ^^^^^^^^^^^^^^^^^                                                                                                                                              File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 137, in _sendExact                                                                             raise FatalTraCIError("Connection closed by SUMO.")                                                                                                                 traci.exceptions.FatalTraCIError: Connection closed by SUMO.  

**SUMO-version1.18:**

**operating system:**

**Comment by m-kro** [comment]
> Then I modified my network that included the pedestrian crossing initial tllogic.

What did you modify exactly? Did the TLS id or the signal program change?

**Comment by khzannat** [comment]
Thank you very much I resolved the issue, I wrongly coded my signal.
