### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ashok-arora** [eclipse-sumo/sumo#14333]
Ran this command:
```bash
python "/usr/share/sumo/tools/randomTrips.py" -n "./environment.net.xml" --validate --seed=0 --random-depart --output "./environment.rou.xml" --trip-attributes="type=\"soulEV65\"" --additional-file "./evehicle.xml" -b 0 -e 5400 -p 6.0
```
and got this error:
```python
Traceback (most recent call last):
  File "/usr/share/sumo/tools/randomTrips.py", line 662, in <module>
    if not main(get_options()):
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/sumo/tools/randomTrips.py", line 574, in main
    departures.append(random.randrange(begin, maxTime))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/py312/lib/python3.12/random.py", line 301, in randrange
    istart = _index(start)
             ^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer
```
so I fixed it by modifying `randomTrips.py` file:
```
- departures.append(random.randrange(begin, maxTime))
+ departures.append(random.randrange(int(begin), int(maxTime)))
```

**SUMO-version:**
```bash
Eclipse SUMO sumo Version 1.12.0
 Build features: Linux-4.15.0-167-generic x86_64 GNU 11.2.0 None Proj GUI SWIG GDAL FFmpeg OSG GL2PS Eigen
 Copyright (C) 2001-2022 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
```

**operating system:**
```bash
Linux iccn 6.5.0-17-generic #17~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan 16 14:32:32 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by m-kro** [comment]
Please update to the latest version. I think this has been fixed looking at the randomTrips.py code.

**Comment by ashok-arora** [comment]
@m-kro Thank you for the suggestion. I do have the latest version i.e. 1.19.0 installled. 
```
(py312) user@iccn:~$ pip show traci
Name: traci
Version: 1.19.0
Summary: The pure python version of the TraCI API to communicate with the traffic simulation Eclipse SUMO
Home-page: https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html
Author: DLR and contributors
Author-email: sumo@dlr.de
License: EPL-2.0
Location: /home/user/miniconda3/envs/py312/lib/python3.12/site-packages
Requires: sumolib
Required-by: 
```
and thats the latest on ubuntu but it did not have it fixed. That's weird. Anyways, thank you once again.

**Comment by m-kro** [comment]
Anyway you can see here that randomTrips.py code has changed:

https://github.com/eclipse-sumo/sumo/blob/9e882d67182e9dc57d8df5716f8de5d02a5dbac0/tools/randomTrips.py#L787-L800

Please note: installing the newest traci module distributed over pypi doesn't get you updated tool scripts or sumo executables. In your first post you showed that you have version 1.12 installed.

**Comment by ashok-arora** [comment]
> Please note: installing the newest traci module distributed over pypi doesn't get you updated tool scripts or sumo executables. In your first post you showed that you have version 1.12 installed.

Oh, I wasn't aware of that. Thank you for the info. :+1:
