### ISSUE TITLE
[Question] Cadyts input file format

### ISSUE THREAD

**Issue by MarMar-s** [eclipse-sumo/sumo#14983]
Hello,

I am trying to use Cadyts to calibrate the flow demand of a small network for 600 seconds. However, when I run Cadyts, it gets stuck at calibration step 0, even after an hour. In the "cadySumo-log.txt" file, I found the following error:

................................................................................................................................
Calibration 2024-06-05 15:20:15 INFO cloning file: C:\Users\mar_mar\Desktop\Scenario_Cadyt\Routes_alternatives.xml
Exception in thread "Thread-0" java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "line" is null
	at floetteroed.cadyts.calibrators.filebased.xml.SAXParserThread.run(SAXParserThread.java:105)
Caused by: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "line" is null
	at floetteroed.utilities.XMLHelpers.extractItems(XMLHelpers.java:62)
	at floetteroed.cadyts.interfaces.sumo.SumoPopulationHandler.startElement(SumoPopulationHandler.java:157)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:519)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2735)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:551)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:890)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:826)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:134)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1225)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:276)
	at floetteroed.cadyts.calibrators.filebased.xml.SAXParserThread.run(SAXParserThread.java:103)
.......................................................................................................................................................
	
	
I have already checked the "Routes_alternatives.xml" file, but I do not know how to solve this issue.

I have attached the "Routes_alternatives.xml" file for your reference. I would greatly appreciate any assistance you could kindly provide.
Thank you so much in advance, 

Best regards,

Maryam SAMAEI

[Routes_alternatives.zip](https://github.com/user-attachments/files/15589192/Routes_alternatives.zip)

**Comment by yunpangfloetteroed** [comment]
Hi, I looked at the file you provided. 
Firstly, it looks like each vehicle has only one route, i.e. there are no route alteratives at all. So, Cadyts cannot work with it, since there is no way to use other routes.
Secondly, all information is in one row. Was this file generated by SUMO? Normally, SUMO does not generate such file.
If you do not have route alterantives, you could run duaIterate.py with your simulation, and use the *.alt.xml of the last iteration as the route alternative file for Cadyts.
I hope that my answer is helpful for you.

**Comment by MarMar-s** [comment]
Thank you very much for your response.

I would like to ask a question regarding Cadyt's functionality. Does Cadyt solely choose between route alternatives, or does it also modify departure times? 
In my network, I have only one route between each origin and destination, as it consists of highways. Therefore, I presumed that Cadyt might adjust the number of sample vehicles in the "Routes_alternatives.xml" file and potentially alter their departure times to match the results to the input detector data.

Thank you so much in advance for your help

**Comment by yunpangfloetteroed** [comment]
Hi, 
- Cadyts is orginally designed to deal with people with different trip plans, i.e. each person/agent has different trip plans, including different departure times, activities and duration for each activity etc. In this sense, each person's departure time can be adjusted by choosing different trip plan for matching given traffic measurements. You can find more information here:  https://api-depositonce.tu-berlin.de/server/api/core/bitstreams/76ff1f2b-1e6f-4caa-ba56-7f34956a3700/content and https://core.ac.uk/reader/147962730 
- In the SUMO-Cadyts coupling, each person has only one trip plan with single origin and destination as well as fixed departure time. So, departure time will not be adjusted. But, when the scale option is used, the whole demand will be scaled, i.e. the original trips will be "cloned".  Then the scaled trips with the depature times, which can result in a better matching to traffic measurements for each interval, would be selected. The un-selected cloned trips will be treated as "stay at home" and not be used. So, using the scale factor does not mean that the whole scaled demand will be considered in the simulation. The scale factor should not be too large. Otherweise, the network could be overloaded, and the overall O-D matrix structure would be twisted. 
- In your case, there is only one route for each OD pair. Thus, the sumo-cadyts coupling does not seem a suitable tool to handle your case. There are other tools to update routes/demands with traffic measurements (see https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html). 
If something is still not clear, please do not hesitate to ask.
