### ISSUE TITLE
 module 'traci.main' has no attribute '_connections'

### ISSUE THREAD

**Issue by SExpert12** [eclipse-sumo/sumo#15121]
Ubuntu: 20
I am running code of this repo of multi-agent system using Sumo.

https://github.com/maxbrenner-ai/Multi-Agent-Distributed-PPO-Traffc-light-control
 When I run the main file, I get this error of Sumo.

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Multi-Agent-Distributed-PPO-Traffc-light-control-master/run_agent_parallel.py", line 17, in train_worker
    worker = PPOWorker(constants, device, env, None, shared_NN, local_NN, optimizer, id)
  File "/home/Multi-Agent-Distributed-PPO-Traffc-light-control-master/workers/ppo_worker.py", line 16, in __init__
    self.state = self.env.reset()
  File "/home/Multi-Agent-Distributed-PPO-Traffc-light-control-master/environments/environment.py", line 77, in reset
    if self.conn_label in traci.main._connections:
AttributeError: module 'traci.main' has no attribute '_connections'
 - Time taken (m): 0.01 - 
Experiment 3 Summary:  rollout: inf  waitingTime: inf  time: 0.01  rew: -inf

How to resolve this?

**Comment by m-kro** [comment]
As you can see from the code, this third-party project relies on some internal TraCI state variable (which may have been refactored since then). The relevant code is in `sumo/tools/traci/connection.py`, so please replace the error line with a call to `traci.connection.has(self.conn_label)`.

**Comment by namdre** [comment]
the change was in  6bb52ed. You could also  downgrade to sumo version 1.15.0 (but @m-kro has the better solution)

**Comment by SExpert12** [comment]
Thank you @namdre and @m-kro for your help and quick reply.
