### ISSUE TITLE
assertion triggered when running in debug mode

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#15223]
in test complex/traci/person/person

**Comment by namdre** [comment]
```
#6  0x00007ffff6c39e96 in __GI___assert_fail (assertion=0x555555fb7838 "pathIt2 != myWalkingAreaPaths.end()", file=0x555555fb7528 "/scr1/sumoD/src/microsim/transportables/MSPModel_Striping.cpp", line=388, 
    function=0x555555fb77b0 "static const MSPModel_Striping::WalkingAreaPath* MSPModel_Striping::getWalkingAreaPath(const MSEdge*, const MSLane*, const MSLane*)") at ./assert/assert.c:101
#7  0x0000555555b8c2f8 in MSPModel_Striping::getWalkingAreaPath (walkingArea=0x555556615de0, before=0x0, after=0x555556612620) at /scr1/sumoD/src/microsim/transportables/MSPModel_Striping.cpp:388
#8  0x0000555555b94a1c in MSPModel_Striping::registerCrossingApproach (ped=..., crossing=0x555556612620, beforeWA=0x0) at /scr1/sumoD/src/microsim/transportables/MSPModel_Striping.cpp:1207
#9  0x0000555555b8cefe in MSPModel_Striping::getNextLane (ped=..., currentLane=0x555556616390, prevLane=0x0) at /scr1/sumoD/src/microsim/transportables/MSPModel_Striping.cpp:488
#10 0x0000555555b97baf in MSPModel_Striping::PState::PState (this=0x555556536dc0, person=0x5555569a7330, stage=0x55555655d9b0, lane=0x555556616390)
    at /scr1/sumoD/src/microsim/transportables/MSPModel_Striping.cpp:1557
#11 0x0000555555b8a3ff in MSPModel_Striping::add (this=0x5555569b76a0, transportable=0x5555569a7330, stage=0x55555655d9b0) at /scr1/sumoD/src/microsim/transportables/MSPModel_Striping.cpp:178
#12 0x0000555555bc53e8 in MSStageWalking::proceed (this=0x55555655d9b0, net=0x5555565380f0, person=0x5555569a7330, now=18000, previous=0x55555655d890)
    at /scr1/sumoD/src/microsim/transportables/MSStageWalking.cpp:136
#13 0x0000555555bc9751 in MSTransportable::proceed (this=0x5555569a7330, net=0x5555565380f0, time=18000, vehicleArrived=false) at /scr1/sumoD/src/microsim/transportables/MSTransportable.cpp:139
#14 0x0000555555bd1b8e in MSTransportableControl::checkWaiting (this=0x55555652f9c0, net=0x5555565380f0, time=18000) at /scr1/sumoD/src/microsim/transportables/MSTransportableControl.cpp:237
#15 0x00005555555b6185 in MSNet::simulationStep (this=0x5555565380f0, onlyMove=false) at /scr1/sumoD/src/microsim/MSNet.cpp:811
#16 0x00005555555af76f in MSNet::simulate (this=0x5555565380f0, start=0, stop=-1000) at /scr1/sumoD/src/microsim/MSNet.cpp:409
#17 0x00005555555ab429 in main (argc=3, argv=0x7fffffffdc08) at /scr1/sumoD/src/sumo_main.cpp:100
```
