### ISSUE TITLE
libsumo importError

### ISSUE THREAD

**Issue by cherryh2021** [eclipse-sumo/sumo#15277]
Hello everyone,

I am trying to run a code of a paper which uses the Libsumo API to interact the SUMO simulator. But I consistently meet with the following error:

Traceback (most recent call last):
  File "d:\research\Macro_and_micro_co-simulation\EGO-centric-SUMO-main\EGO-centric-SUMO-main\simulate_town_cosim.py", line 5, in <module>
    from libsumo_parallel import *
  File "d:\research\Macro_and_micro_co-simulation\EGO-centric-SUMO-main\EGO-centric-SUMO-main\libsumo_parallel.py", line 8, in <module>
    import libsumo
  File "E:\SUMO\tools\libsumo\__init__.py", line 30, in <module>
    from .libsumo import vehicle, simulation, person, trafficlight  # noqa
  File "E:\SUMO\tools\libsumo\libsumo.py", line 13, in <module>
    from . import _libsumo
ImportError: DLL load failed while importing _libsumo: The specified module could not be found.

Can anyone help me fix it? Thanks a lot!

**Comment by behrisch** [comment]
@cherryh2021 Please give more information: Especially how you installed libsumo and what is your python and SUMO version?

**Comment by behrisch** [comment]
@cherryh2021 Sorry for the delay. Does this mean you installed libsumo via `pip install libsumo==1.15.0`? Or do you have another sumo installed which is version 1.15.0? If it is the latter please try to uninstall it or at least check whether your SUMO_HOME environment variable points to that installation and if so unset it and try again.

**Comment by behrisch** [comment]
Closing for lack of feedback. A frequent reason for this kind of error is a missing library. Try to use something like https://github.com/lucasg/Dependencies to analyze the installed libsumo.pyd for missing libraries
