### ISSUE TITLE
error on  using fuction  traci.trafficlight.setProgramLogic(tls_id, logic) in python

### ISSUE THREAD

**Issue by sjh30** [eclipse-sumo/sumo#15291]
i have one question on using the fuction traci.trafficlight.setProgramLogic(tls_id, logic) in python 
here is my code:
``` 
phases = []
phases.append(traci.trafficlight.Phase(30, "rrrrGGggrrrrGGgg",0, 0,[1]))
phases.append(traci.trafficlight.Phase(10, "rrrrGGggrrrrGGgg",0, 0,[0]))

# 创建交通灯逻辑
logic = traci.trafficlight.Logic("custom", 0, 1, phases)
print(logic)
# 在仿真中设置交通灯逻辑
tls_id ='J2'

traci.trafficlight.setProgramLogic(tls_id, logic)
```
And here is the wrong message:

Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\pythonforsumo\pythonforsumo1.py", line 133, in <module>
    run_simulation()
  File "C:\Users\admin\PycharmProjects\pythonforsumo\pythonforsumo1.py", line 112, in run_simulation
    traci.trafficlight.setProgramLogic(tls_id, logic)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\_trafficlight.py", line 420, in setProgramLogic
    self._setCmd(tc.TL_COMPLETE_PROGRAM_RYG, tlsID, format, *values)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\domain.py", line 164, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 231, in _sendCmd
    return self._sendExact()
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 144, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Mismatching phase size in tls 'J2', program 'custom'.

I dont understand that ,J2 only has two phases  and the current phaseindex=1;so  why the wrong message is  Mismatching phase size in tls 'J2' .

**SUMO-version:1.19

**operating system:windows

**Comment by m-kro** [comment]
That's not what the error message is about. The number of signal states (the single letters in the phases) has to match the number of controlled links of the traffic light (which doesn't seem to be the case).

**Comment by sjh30** [comment]
Thanks a lot,the problem is solved right now.
