### ISSUE TITLE
Error when using fcdReplay.py

### ISSUE THREAD

**Issue by vietanhle0101** [eclipse-sumo/sumo#15320]
Hello,

I tried to use fcdReplay.py tool to replay a simulation, but I got the following error:"

```
Traceback (most recent call last):
  File "/home/vietanhle/github/TLS_CAV_MixedTraffic/fcdReplay.py", line 92, in <module>
    main()
  File "/home/vietanhle/github/TLS_CAV_MixedTraffic/fcdReplay.py", line 76, in main
    traci.poi.add(obj.id, obj.x, obj.y, (255, 0, 0))
  File "/home/vietanhle/github/phdenv/lib/python3.10/site-packages/traci/_poi.py", line 137, in add
    self._setCmd(tc.ADD, poiID, "tsciosddds", 9, poiType, color, layer, (x, y), imgFile, width, height, angle, icon)
  File "/home/vietanhle/github/phdenv/lib/python3.10/site-packages/traci/domain.py", line 164, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "/home/vietanhle/github/phdenv/lib/python3.10/site-packages/traci/connection.py", line 231, in _sendCmd
    return self._sendExact()
  File "/home/vietanhle/github/phdenv/lib/python3.10/site-packages/traci/connection.py", line 144, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Adding a PoI requires either only type, color, layer and position parameters or these and imageFile, width, height and angle parameters.
```

Let me know how to fix this error.

**Comment by m-kro** [comment]
Which SUMO version do you use?

**Comment by behrisch** [comment]
Closing for lack of feedback

**Comment by EANiloy** [comment]
I am using Sumo version 1.8.0, when I try to add a poi using sumo, I also get the same error.
My code,
`traci.poi.add(poiID="poiId_1", x=0.0, y=0.0, color=(0,0,255,255), poiType="em", layer=202)`
I get the error,
`traci.exceptions.TraCIException: Adding a PoI requires either only type, color, layer and position parameters or these and imageFile, width, height and angle parameters.`
