### ISSUE TITLE
[Question] Problems Running Simulations after Network Modifications

### ISSUE THREAD

**Issue by jamongadejoa28** [eclipse-sumo/sumo#15376]
Add your issue description here.
Problem when running the following code.

```
  import os
  import sys
  import subprocess
  import traceback
  import optparse
  import traci
  from sumolib import net
  import xml.etree.ElementTree as ET
  
  if 'SUMO_HOME' in os.environ:
      sumo_home = os.environ['SUMO_HOME']
      tools = os.path.join(sumo_home, 'tools')
      sys.path.append(tools)
  else:
      sys.exit("please declare environment variable 'SUMO_HOME'")
  
  from sumolib import checkBinary
  
  def create_sumo_rou():
      random_trips = os.path.join(tools, 'randomTrips.py')
      subprocess.run([sys.executable, random_trips, "-n", "data/test.net.xml", "-r", "data/test.rou.xml", "-p", "0.2",
                      "--binomial", "10","-e", "3600", "-l","--random", "--random-factor","1.2", "--random-depart"], check=True)
  
      subprocess.run(["duarouter", "-n", "data/test.net.xml", "-r", "data/test.rou.xml",
                      "-e", "3600", "-o", "data/duaroute.xml", "--ignore-errors", "--routing-algorithm", "astar",
                      "--repair", ], check=True)
  
      subprocess.run(["sumo", "-n", "data/test.net.xml", "-r", "data/duaroute.xml",
                      "--save-configuration", "data/test.sumocfg"], check=True)
  
  
  def change_laneNumber(net_file):
      # Parse the XML file
      tree = ET.parse(net_file)
      root = tree.getroot()
  
      # Find all edge elements
      edges = root.findall('.//edge')
      modified = False
  
      for edge in edges:
          # Count the number of lanes in this edge
          lanes = edge.findall('lane')
          if len(lanes) == 1:
              existing_lane = lanes[0]
              lane_id_parts = existing_lane.get('id').rsplit('_', 1)
              lane_id_base = lane_id_parts[0]
              lane_index = int(lane_id_parts[1])
  
              # Add two new lanes
              for i in range(1, 3):
                  new_lane = ET.Element('lane')
                  new_index = lane_index + i
                  new_lane.set('id', f"{lane_id_base}_{new_index}")
                  new_lane.set('index', str(new_index))
  
                  # Copy all attributes from the existing lane except 'id' and 'index'
                  for attr, value in existing_lane.attrib.items():
                      if attr not in ['id', 'index']:
                          new_lane.set(attr, value)
  
                  # Append the new lane to the edge
                  edge.append(new_lane)
  
              modified = True
  
      if modified:
          # Save the modified XML back to the file
          tree.write(net_file, encoding='utf-8', xml_declaration=True)
          print(f"Network file {net_file} has been modified. Added 2 lanes to single-lane edges.")
      else:
          print("No single-lane edges found. No modifications were made.")
  
  def run():
      step = 0
      try:
          while traci.simulation.getMinExpectedNumber() > 0:
              traci.simulationStep()
              step += 1
      except Exception as e:
          print(e)
      finally:
          traci.close()
  
  def get_options():
      optParser = optparse.OptionParser()
      optParser.add_option("--nogui", action="store_true", default=False, help="run the commandline version of sumo")
      options, args = optParser.parse_args()
      return options
  
  if __name__ == "__main__":
      options = get_options()
      if options.nogui:
          sumoBinary = checkBinary('sumo')
      else:
          sumoBinary = checkBinary('sumo-gui')
      cmd = [sumoBinary, "-c", "data/test.sumocfg", "--fcd-output", "data/fcd.xml"]
  
      try:
          net_file= "data/test.net.xml"
          change_laneNumber(net_file)
          create_sumo_rou()
          traci.start(cmd)
          run()
      except Exception as e:
          traceback.print_exc()
          print(f"Unexpected error during simulation: {e}")
          exit(1)
      finally:
          try:
              traci.close()
          except:
              pass
```

I modified my network so that an edge with 1 lane had 3 lanes, but I ran into a problem.

*If possible, upload an example that shows your problem.*
```
C:\Users\SMART-01\PycharmProjects\sumopj\.venv\Scripts\python.exe C:\Users\SMART-01\PycharmProjects\sumopj\runner.py Network file data/test.net.xml has been modified. Added 2 lanes to single-lane edges. Success. Success. Traceback (most recent call last): File "C:\Users\SMART-01\PycharmProjects\sumopj\runner.py", line 122, in <module> traci.start(cmd) File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py", line 147, in start result = init(sumoPort, numRetries, "localhost", label, sumoProcess, doSwitch, traceFile, traceGetters) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py", line 119, in init return con.getVersion() ^^^^^^^^^^^^^^^^ File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 381, in getVersion result = self._sendCmd(command, None, None) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 231, in sendCmd return self.sendExact() ^^^^^^^^^^^^^^^^^ File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 137, in _sendExact raise FatalTraCIError("Connection closed by SUMO.") traci.exceptions.FatalTraCIError: Connection closed by SUMO. Unexpected error during simulation: Connection closed by SUMO. Process finished with exit code 1
```
Network file open fine in netedit without any critical errors. However, this do not open in the GUI and automatically close the GUI program.

**SUMO-version:**

**operating system:**
PyCharm 2024.2 (Community Edition)
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by m-kro** [comment]
Please do not modify the network file directly, see [FAQ] (https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why)

**Comment by jamongadejoa28** [comment]
@m-kro 
If so, should the number and type of lanes on an edge only be modified with netedit, but not with a python script?

**Comment by namdre** [comment]
you can use a python script that calls netconvert. see https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_node_positions_with_the_help_of_sumolib
and https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_the_network

**Comment by jamongadejoa28** [comment]
@namdre 
Thank you so much, why didn't I find this information? My stupidity...haha
