### ISSUE TITLE
cannot connect to TraCI on the server

### ISSUE THREAD

**Issue by gene637** [eclipse-sumo/sumo#15556]
can't run sumo on a server.

*If possible, upload an example that shows your problem.*
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 45403 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 54507 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 44547 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 54645 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 36505 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55973 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 48737 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 40089 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 40923 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 53591 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 51803 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 45469 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 33679 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55073 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 34117 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 36503 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 36729 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 57541 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 60955 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 51943 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 37739 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55917 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55569 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 53841 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 60037 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 60633 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 36971 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 42671 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 47029 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 48077 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 53633 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 49021 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 60801 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 48847 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 44419 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 58279 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 36059 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 45987 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 51303 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 43685 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 58265 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 34131 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 59095 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 51123 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 38627 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 35431 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 34899 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 44259 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 45499 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 51565 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 38509 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 52799 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 45487 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 58111 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 51877 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55417 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 60907 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 45317 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55307 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 58703 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 44367 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Traceback (most recent call last):
  File "CLA-ET-LLon_new_24h.py", line 140, in <module>
    "64", "--device.rerouting.synchronize", "true", "--time-to-teleport", "100", "--tripinfo-output", save_folder+"tripinfo.xml"])
  File "/rhome/zzhan554/.local/lib/python3.9/site-packages/sumo/tools/traci/main.py", line 157, in start
    raise FatalTraCIError("Could not connect.")
traci.exceptions.FatalTraCIError: Could not connect.

**SUMO-version:**
1.20.0
**operating system:**
LINUX

**Comment by namdre** [comment]
Most likely, the simulation aborts with an error. 
Add option `"-l", "log.txt",` to `traci.start` and check the contents of log.txt.

**Comment by gene637** [comment]
Thanks.
Actually, after I set '--device.rerouting.threads' from 64 to 0, it works.
I guess it does not support multiple threads running. Any thoughts?

thanks

Jakob Erdmann ***@***.***> 于 2024年10月7日周一 01:02写道：

**Comment by namdre** [comment]
Did you check the log file? Was there an error message or a crash?
In case it's the latter, feel free to send minimal input files for replicating the crash.

**Comment by behrisch** [comment]
closing for lack of feedbak
