### ISSUE TITLE
Homebrew installation with SUMO 1.20 causes several problems

### ISSUE THREAD

**Issue by phil-hei** [eclipse-sumo/sumo#15630]
I followed the instruction given [here](https://github.com/DLR-TS/homebrew-sumo) to install SUMO via Homebrew, but I don't get it run as there seems to be some more problems with my installation.

First of all, the installation via Homebrew went smooth and `brew info sumo` give me the following:

```
==> dlr-ts/sumo/sumo: stable 1.20.0 (bottled), HEAD
Simulation of Urban MObility
https://www.eclipse.dev/sumo
Installed
/opt/homebrew/Cellar/sumo/1.20.0.reinstall (1,812 files, 155.9MB)
  Poured from bottle on 2024-10-23 at 14:40:10
From: https://github.com/dlr-ts/homebrew-sumo/blob/HEAD/Formula/sumo.rb
License: EPL-2.0
==> Dependencies
Build: cmake ✔
Required: fontconfig ✔, fox ✔, freetype ✔, gettext ✔, jpeg-turbo ✔, libice ✔, libpng ✔, libtiff ✔, libx11 ✔, libxcursor ✔, libxext ✔, libxfixes ✔, libxft ✔, libxi ✔, libxrandr ✔, libxrender ✔, mesa ✔, mesa-glu ✔, proj ✔, xerces-c ✔
Optional: ffmpeg ✘, gdal ✘, gl2ps ✔, open-scene-graph ✔, swig ✔
==> Options
--with-examples
	Install docs/examples and docs/tutorial folder
--with-ffmpeg
	Build with ffmpeg support
--with-gdal
	Build with gdal support
--with-gl2ps
	Build with gl2ps support
--with-open-scene-graph
	Build with open-scene-graph support
--with-swig
	Build with swig support
--HEAD
	Install HEAD version
==> Caveats
In order to let X11 start automatically whenever a GUI-based SUMO application
(e.g., "sumo-gui") is called, you need to log out and in again.
Alternatively, start X11 manually by pressing cmd-space and entering "XQuartz".

Don't forget to set your SUMO_HOME environment variable:
  export SUMO_HOME="/opt/homebrew/Cellar/sumo/1.20.0/share/sumo"

Please report any problems with this formula directly to the eclipse-sumo/sumo issue tracker:
https://github.com/eclipse-sumo/sumo/issues
```

However, using `sumo` or `sumo-gui` give me just back `zsh: command not found: sumo`, although I've set the SUMO_HOME path to "/opt/homebrew/Cellar/sumo/1.20.0.reinstall/share/sumo" - I wonder here already that it is called "1.20.0.reinstall". 

When navigating manually to the bin folder (/opt/homebrew/Cellar/sumo/1.20.0.reinstall/share/sumo/bin) and starting sumo (`./sumo`), I get the following error:

```
dyld[26261]: Library not loaded: /opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib
  Referenced from: <1FCAEFA0-3B2A-3E81-97EB-31D48936B9B5> /opt/homebrew/Cellar/sumo/1.20.0.reinstall/bin/sumo
  Reason: tried: '/opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib' (no such file), '/opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib' (no such file), '/opt/homebrew/Cellar/xerces-c/3.3.0/lib/libxerces-c-3.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/xerces-c/3.3.0/lib/libxerces-c-3.2.dylib' (no such file), '/opt/homebrew/Cellar/xerces-c/3.3.0/lib/libxerces-c-3.2.dylib' (no such file)
```
  
I already tried to uninstall sumo and xerces via brew, delete the cache that I found and then reinstalled sumo again, but still the same problem. I probably have worsen it through my debugging. Any hints what can cause the problems and how to fix it? What is the best way to install everything from scratch?

**SUMO-version:**
1.20.0

**operating system:**
macOS Sequoia 15.0.1 (24A348)

**Comment by ry-sny** [comment]
I'm also having this issue

**Comment by Eubulon3** [comment]
I'm also having this issue

**Comment by JaydenGao-gjd** [comment]
I also having this issue. So I installed SUMO by downloading source code.

**Comment by barbourww** [comment]
Also having the issue. I confirmed installation of xerces-c version 3.3.0. Does not appear that Homebrew supports downgrading in order to get the 3.2.0 that SUMO is apparently looking for.

**Comment by bz247** [comment]
I had the same problem and installed `libxerces-c-3.2.dylib` manually. I am not sure if it is a good practice to have two versions of libxerces installed, but it works...

1. Download `xerces-c-3.2.5.tar.gz` from https://archive.apache.org/dist/xerces/c/3/sources/

2. Install based on this instruction (UNIX -- source distribution) https://xerces.apache.org/xerces-c/install-3.html
```
gzip -d xerces-c-3.2.5.tar.gz
tar -xf xerces-c-3.2.5.tar
```
You may need to save it to a suitable location on your computer. 

3. Use `cmake` to build
```
cd xerces-c-3.2.5
mkdir build
cd build
cmake ..
make
make install
```

At the end, at least `sumo-gui` opens normally. Haven't tested the functions further.

**Comment by Mafumaful** [comment]
I came across the same problem, I solved the problem by:
```zsh
brew reinstall xerces-c 
```

**Comment by vtghsr** [comment]
> I came across the same problem, I solved the problem by:
> 
> brew reinstall xerces-c

Thanks. It works for me. And don't forget to restart the shell after reinstall.

**Comment by AndriiBabushko** [comment]
> I came across the same problem, I solved the problem by:
> 
> brew reinstall xerces-c

It helps on macos 15.2. Good job

**Comment by palikao** [comment]
I'm having this kind of misterious issue:
`brew install sumo       
==> Downloading https://formulae.brew.sh/api/formula.jws.json
Error: Return value: Expected type String, got type BuildOptions with hash -1676944769641108508
Caller: /opt/homebrew/Library/Taps/dlr-ts/homebrew-sumo/Formula/sumo.rb:41
Definition: /opt/homebrew/Library/Homebrew/formula.rb:3707 (Formula.build)
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/configuration.rb:303:in `call_validation_error_handler'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:322:in `report_error'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:291:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Taps/dlr-ts/homebrew-sumo/Formula/sumo.rb:41:in `<class:Sumo>'
/opt/homebrew/Library/Taps/dlr-ts/homebrew-sumo/Formula/sumo.rb:1:in `block in load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:109:in `module_eval'
/opt/homebrew/Library/Homebrew/formulary.rb:109:in `block in load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:121:in `load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:152:in `load_formula_from_path'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:282:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:282:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/formulary.rb:528:in `load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:734:in `load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:519:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:514:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:724:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:927:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:282:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:282:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/parser.rb:728:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:724:in `each'
/opt/homebrew/Library/Homebrew/cli/parser.rb:724:in `filter_map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:724:in `formulae'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:282:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:282:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/parser.rb:381:in `parse'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:179:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:179:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:121:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/abstract_command.rb:68:in `initialize'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:282:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/call_validation.rb:282:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/abstract/declare.rb:37:in `new'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11851/lib/types/private/abstract/declare.rb:37:in `block in declare_abstract'
/opt/homebrew/Library/Homebrew/brew.rb:91:in `<main>'`

**Comment by angelobanse** [comment]
@palikao we no longer maintain the installation via Homebrew. Please try the new [macOS installer](https://sumo.dlr.de/docs/Downloads.php#macos).
