### ISSUE TITLE
traci.exceptions.FatalTraCIError: Not connected.

### ISSUE THREAD

**Issue by MoMingQimio** [eclipse-sumo/sumo#15647]
Traceback (most recent call last):
  File "E:\xuhaocheng\GABA\train.py", line 476, in <module>
    train()
  File "E:\xuhaocheng\GABA\train.py", line 463, in train
    env.closeEnvConnection()
  File "E:\xuhaocheng\GABA\SUMO-RL-ENVIRONMENT\gym_sumo\envs\sumo_env.py", line 397, in closeEnvConnection
    traci.close()
  File "D:\software\sumo\tools\traci\main.py", line 262, in close
    connection.check().close(wait)
  File "D:\software\sumo\tools\traci\connection.py", line 45, in check
    raise FatalTraCIError("Not connected.")
traci.exceptions.FatalTraCIError: Not connected.

here is the reported error, I want to know why the exception can happen every time

**Comment by m-kro** [comment]
Difficult to say without knowing more about your TraCI script. Could it be that you call `traci.close` twice by accident?

**Comment by MoMingQimio** [comment]
Here is my code:  https://github.com/MoMingQimio/GABA.git
Error always happens at about 210 episode

**Comment by m-kro** [comment]
You have a file where you may call `traci.close` multiple times: **dqn_sumo_gym.py** lines 252 and 263.
