### ISSUE TITLE
GTFS Import: Relied on optional 'direction_id' column 

### ISSUE THREAD

**Issue by hoesLu** [eclipse-sumo/sumo#15736]
Dear SUMO team,

I am trying to import GTFS data to make public transport lines run on schedule in my simulation. For the import I tried to (re-)create a minimal example. In particular I did the following:

1. I downloaded the network through the OSM webwizard and made sure I ticked the `"Import public transport"` box.
2. I downloaded GTFS data from the [GTFS webpage](https://gtfs.de/de/feeds/de_nv/ )
3. I unpacked the files `osm.net.xml.gz`, `osm_bbox.osm.xml.gz` and `osm.poly.xml.gz` to have `osm.net.xml`, `osm_bbox.osm.xml` and `osm.poly.xml`. 
4. I followed the instruction by your [webpage ](https://sumo.dlr.de/docs/Tutorials/GTFS.html) to map GTFS and OSM data. In particular, I excuted the command
 `python tools/import/gtfs/gtfs2pt.py -n osm.net.xml --gtfs latest.zip --date 20241118 --osm-routes osm_ptlines.xml --repair --vtype-output gen_pt_vtypes.xml` 
 
 
This gives me the following output:
```

function import_gtfs called at Mon, 18 Nov 2024 12:44:37 +0000
function import_gtfs finished after 48.345740 seconds
Warning: GTFS shapes file not found! Continuing mapping without shapes.
function filter_gtfs called at Mon, 18 Nov 2024 12:45:25 +0000
Traceback (most recent call last):
  File "C:\Users\hoes_lu\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'direction_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/import/gtfs/gtfs2pt.py", line 475, in <module>
    main(get_options())
  File "tools/import/gtfs/gtfs2pt.py", line 412, in main
    stops, stop_times)
  File "C:\Users\hoes_lu\Sumo\tools\sumolib\miscutils.py", line 49, in benchmark_wrapper
    result = func(*args, **kwargs)
  File "C:\Users\hoes_lu\Documents\programs\sumo-win64extra-1.21.0\sumo-1.21.0\tools\import\gtfs\gtfs2osm.py", line 228, in filter_gtfs
    gtfs_data['shape_id'] = gtfs_data['route_id'] + "_" + gtfs_data['direction_id']
  File "C:\Users\hoes_lu\AppData\Roaming\Python\Python37\site-packages\pandas\core\frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\hoes_lu\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'direction_id'
```

Indeed, I could not find a `direction_id ` in any of my GTFS files. Still, I am confident to have used the correct source for my GTFS data. How could this problem be resolved? Thank you very much!

**Comment by m-kro** [comment]
The official [GTFS reference](https://gtfs.org/documentation/schedule/reference/#tripstxt) lists `direction_id` as optional. Then we should follow the reference and check for availability.

**Comment by m-kro** [comment]
@hoesLu Can you try whether the patched script works for you? Just download it from Github source or use the[ latest dev version download](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version).

**Comment by hoesLu** [comment]
Thank you very much @m-kro, GTFS import works now! 
Meaning it works for the one line that lies entirely inside my SUMO network. There are a couple of other public transport lines crossing my network (that means only a part of these lines is represented in SUMO). Is there a way to get GTFS data for those as well?

**Comment by m-kro** [comment]
@hoesLu Can you name the GTFS source and the OSM border coordinates of your scenario? In my example scenario there are pt lines which have been cut included...

**Comment by hoesLu** [comment]
@m-kro , this is the location data from my .net.xml:.

`<location netOffset="-1169325.02,-6852062.07" convBoundary="0.00,0.00,2115.25,1484.90" origBoundary="10.504225,52.286304,10.523227,52.294478" projParameter="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"/>`

in case this information does not help you, the geo-coordinates from sumo gui are

lat: 52.294504, lon: 10.497667
lat: 52.286333, lon: 10.497701
lat: 52.286343, lon: 10.529738
lat: 52.294494, lon: 10.529755.

Thanks again:)

**Comment by m-kro** [comment]
Looks like the script has to emulate a missing **direction_id** somehow to make all subsequent data processing work correctly. Without the **direction_id** one direction is thrown away (merged/grouped)...

**Comment by m-kro** [comment]
@hoesLu Feel free to try the latest update. The missing "direction_id" is now emulated internally so that public transport trips of both directions are imported.

**Comment by hoesLu** [comment]
Thank you very much for your help! Indeed, the GTFS import works better now. Still, I have a few problems:

1. There is no GTFS import for bus line 414. This issue is also reported by the `gtfs_missing.xml`  
```
<missingElements>
<stop id="122430" name="Braunschweig, Sielkamp" ptLine="414" direction_id="b5b4204bd4f12faf667b5c3dc273f6ec"/>
<stop id="122430" name="Braunschweig, Sielkamp" ptLine="414" direction_id="e3f848c5381fbb4016730806bcd09e1c"/>
<stop id="223206" name="Braunschweig, Ligusterweg" ptLine="414" direction_id="b5b4204bd4f12faf667b5c3dc273f6ec"/>
<stop id="223206" name="Braunschweig, Ligusterweg" ptLine="414" direction_id="e3f848c5381fbb4016730806bcd09e1c"/>
<stop id="239434" name="Braunschweig, Weizenbleek" ptLine="414" direction_id="b5b4204bd4f12faf667b5c3dc273f6ec"/>
<stop id="239434" name="Braunschweig, Weizenbleek" ptLine="414" direction_id="e3f848c5381fbb4016730806bcd09e1c"/>
<stop id="415279" name="Braunschweig, Schlehenhang" ptLine="414" direction_id="b5b4204bd4f12faf667b5c3dc273f6ec"/>
<stop id="415279" name="Braunschweig, Schlehenhang" ptLine="414" direction_id="e3f848c5381fbb4016730806bcd09e1c"/>
</missingElements>
```
How can I get this right?

2. Tram line 2 does run a short part inside the network, but is not represented in the `gtfs_pt_vehicles.add.xml`. Is there a way to import GTFS data also for this part?

3. Tram lines 1 and 10 only run in one direction:
```
<stop busStop="1025292.0" duration="10" until="0"/> <!-- Braunschweig, Gesundheitsamt (Wasserwelt) -->
<stop busStop="1025292.1" duration="10" until="120"/> <!-- Braunschweig, Stadion (Schwarzer Berg) -->
```
the opposite direction from Stadion to Gesundheitsamt is not imported. Was this the same for you?

4. Also, all routes for line 1 and 10 in the  `gtfs_pt_vehicles.add.xml` file end at stop Stadion, even though the schedule of line 1 continues towards Schmalbachstraße. If this is just the normal inteded behaviour of the script I can also quick fix this on my own. 

I tried the GTFS import with both solutions, Routes from shortest path and OSM. The issues are the same for both methods.
Any help is very much appreciated (especially for point 1 and 3). Thanks!

**Comment by hoesLu** [comment]
@m-kro, thanks for your help; I found the problem: My original network did not contain all the stops for lines I wanted to simulate. I slightly extended the network borders; now it works
