### ISSUE TITLE
crash on isertion at rail crossing with pedestrians

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#15807]
regression via  #14928 in 1.21.0

`MSLink::hasApproachingFoe` calls `blockedAtTime` without ego argument and this case isn't handled later when there are conflicting pedestrians

**Comment by namdre** [comment]
also shows up without rail_crossing in the context of lane changing ahead of intersections (in acosta_stripling!)

```
0x00005555557b891a in MSLink::blockedAtTime (this=0x555556f26bd0, arrivalTime=2814463, leaveTime=2816162, arrivalSpeed=10.391438832038611, leaveSpeed=10.391438832038611, sameTargetLane=false, impatience=0, decel=4.5, waitingTime=0, collectFoes=0x0, ego=0x0, lastWasContRed=false, dist=-1) at /scr1/sumoD/src/microsim/MSLink.cpp:943
943                     const auto& cfm = ego->getVehicleType().getCarFollowModel();
(gdb) bt
#0  0x00005555557b891a in MSLink::blockedAtTime (this=0x555556f26bd0, arrivalTime=2814463, leaveTime=2816162, arrivalSpeed=10.391438832038611, leaveSpeed=10.391438832038611, sameTargetLane=false, impatience=0, 
    decel=4.5, waitingTime=0, collectFoes=0x0, ego=0x0, lastWasContRed=false, dist=-1) at /scr1/sumoD/src/microsim/MSLink.cpp:943
#1  0x00005555557b9378 in MSLink::hasApproachingFoe (this=0x555556e60830, arrivalTime=2814463, leaveTime=2816162, speed=10.391438832038611, decel=4.5) at /scr1/sumoD/src/microsim/MSLink.cpp:1132
#2  0x00005555556aada1 in MSVehicle::unsafeLinkAhead (this=0x555557b0c120, lane=0x555556d49360) at /scr1/sumoD/src/microsim/MSVehicle.cpp:6955
#3  0x00005555557a320b in MSLaneChanger::checkChange (this=0x555556f804b0, laneOffset=-1, targetLane=0x555556d49360, leader={...}, follower={...}, neighLead={...}, neighFollow={...}, 
    preb=std::vector of length 4, capacity 4 = {...}) at /scr1/sumoD/src/microsim/MSLaneChanger.cpp:934
#4  0x00005555557a2469 in MSLaneChanger::checkChangeWithinEdge (this=0x555556f804b0, laneOffset=-1, leader={...}, preb=std::vector of length 4, capacity 4 = {...})
    at /scr1/sumoD/src/microsim/MSLaneChanger.cpp:740
#5  0x00005555557a09e6 in MSLaneChanger::change (this=0x555556f804b0) at /scr1/sumoD/src/microsim/MSLaneChanger.cpp:342
#6  0x000055555579fd5a in MSLaneChanger::laneChange (this=0x555556f804b0, t=2814000) at /scr1/sumoD/src/microsim/MSLaneChanger.cpp:149
#7  0x000055555572b948 in MSEdge::changeLanes (this=0x555556d47c60, t=2814000) at /scr1/sumoD/src/microsim/MSEdge.cpp:842
#8  0x0000555555747cef in MSEdgeControl::changeLanes (this=0x555556f9a190, t=2814000) at /scr1/sumoD/src/microsim/MSEdgeControl.cpp:288
```
